### ISSUE TITLE
Clean up src/ directory

### ISSUE THREAD

**Issue by beckyjackson** [IEDB/MRO#102]
The `src/` directory contains a bunch of Python scripts, but we also have scripts in `src/scripts/`.

I propose we create a new `queries/` directory to hold all `.rq` and `.sql` files, and then move all `.py` files to `src/scripts`. Since we have so many Python scripts, maybe we could even break down `src/scripts/` into more categories? 

Also, there is `src/mro/`, which I'm not sure anything is used in. I think it was last updated 6 years ago. @jamesaoverton do you know if this can be removed?

**Comment by jamesaoverton** [comment]
The old `src/mro/` can be deleted. Please reorganize as you see fit, but keep @acrinklaw informed.
