### ISSUE TITLE
Handle upstream sequence changes

### ISSUE THREAD

**Issue by beckyjackson** [IEDB/MRO#42]
Running `make update-seqs` retrieves the latest version of https://github.com/ANHIG/IMGTHLA/raw/Latest/hla_prot.fasta for HLAs. Upstream changes will cause the sequences in MRO to change, like in #41.

We should make sure that this doesn't break anything, or perhaps only retrieve changes periodically and review them.

**Comment by beckyjackson** [comment]
Duplicate with #43

**Comment by beckyjackson** [comment]
Duplicate with #43

**Comment by rvita** [comment]
we want MRO to stay up to date with IMGT, they are the SOT for the sequences, so we should have a schedule to check for updates & change MRO to match IMGT if any changes are found.
