### ISSUE TITLE
Implement validation script

### ISSUE THREAD

**Issue by jamesaoverton** [IEDB/MRO#44]
We recently added ROBOT validation, but it's causing performance problems with the large set of HLAs about to land, and it doesn't cover important cases such as validating patterns for names. I'd like an MRO validation script written in Python and outputting a "standard problems table" that COGS can read. We have one of these for ONTIE: https://github.com/IEDB/ONTIE/blob/master/src/scripts/report.py

**Comment by beckyjackson** [comment]
Do you think this `report.py` script is something we should add to `gizmos`?
