### ISSUE TITLE
Set up DROID workflow

### ISSUE THREAD

**Issue by beckyjackson** [IEDB/MRO#47]
We should add a DROID workflow to the Makefile, which includes COGS & validation tasks:

1. Create Google Sheet
2. Edit Sheets
3. Validate Sheets
4. Build Files
5. View Results

Is there anything I'm missing? The Version Control tasks already in DROID should take care of everything else. We may want to add a "Release" task as well?

**Comment by beckyjackson** [comment]
I think releasing might be easier to do just on the command line since you need to create & attach the binaries to the release anyway...

**Comment by jamesaoverton** [comment]
For the release, please try to use the latest GitHUb CLI https://cli.github.com/manual/gh_release. Looks like release functionality was recently added.

**Comment by beckyjackson** [comment]
@jamesaoverton - We want Randi to switch to this from using the XLSX sheet, correct? So she will be the user, not me?

**Comment by jamesaoverton** [comment]
I want Randi to be doing most of the editing, using a Google Sheet. You and I will still be checking the results and making releases.

**Comment by beckyjackson** [comment]
OK - just making sure. So the `ontology/` directory is now the source of truth, rather than the Excel sheet. Thanks!

**Comment by jamesaoverton** [comment]
The `ontology/` directory was always the source of truth, which is why it was stored in git. Excel was used for editing convenience, and now we'll use Google Sheets for editing convenience.

**Comment by rvita** [comment]
where is the google sheet & can I start using it now?

**Comment by beckyjackson** [comment]
I forgot a step in the workflow. We need to assign IDs for the new terms.
1. Edit Google Sheet
2. Assign IDs (moving new terms to index & adding IDs to iedb table)
3. Validate Tables
4. Prepare Products (building mro.owl for tree/term table)
5. Validate Products (e.g., ROBOT queries)
6. Browse tree and/or term table

I'll make a separate release workflow. Is having the two separate validation steps too confusing? I was thinking the "validate tables" should be run before building the products because it helps to make sure the inputs are sane (e.g., no missing labels in index). "validate products" runs stuff over `mro.owl`, so that needs to be created first anyway.

@rvita there won't be one "source of truth" Google sheet, but DROID will create a new Google sheet based on the TSVs in the repository and then you'll be able to edit that one. For right now, please keep sending me the updates in the Excel sheet! 🙂
