### ISSUE TITLE
add MRO ID to molecule.tsv

### ISSUE THREAD

**Issue by jgbaum** [IEDB/MRO#99]
Is it possible to add the MRO ID as a column in the [molecule.tsv](ontology/molecule.tsv) file?  That would be useful for the IEDB Tools.

Thanks and let me know if you need more info.

-J

**Comment by jamesaoverton** [comment]
I'd rather not add a column to that file, but we can make another table to suit your needs. Which columns do you want?

**Comment by jgbaum** [comment]
A custom export...nice!

Using the names from the current molecule.tsv, we would like the following columns in our export:

* MRO ID
* Label
* IEDB Label
* Synonyms
* Parent (if this could be provided as an MRO ID instead of label, that would be preferred.  If that's a pain, no problem).
* In Taxon

Please let me know if you need any more info.

Thanks!

-J

**Comment by beckyjackson** [comment]
Do you want the label or the NCBITaxon ID for "In Taxon"?

**Comment by jgbaum** [comment]
Hmmm...we've been working with the labels so far so we should probably keep that.  Maybe let's have both (in two separate columns), if possible?

Thank you!

-J
